name: Simple Docker Build, Scan, and Push

on:
  push:
    branches:
      - main  # Déclenche le workflow lors d'un push sur la branche "main"

jobs:
  build:
    runs-on: ubuntu-latest  # Utilisation de l'environnement Ubuntu pour l'exécution du job
    # Permissions nécessaires pour accéder à GitHub Packages
    permissions:
      contents: read  # Permission de lecture sur le contenu du dépôt
      packages: write  # Permission d'écriture pour les packages Docker
      actions: read  # Permission de lecture sur les actions
      id-token: write  # Permission pour générer un ID token pour l'authentification

    steps:
      # Étape 1 : Vérifier le code source du dépôt
      - name: Checkout code
        uses: actions/checkout@v3  # Mise à jour vers la dernière version de l'action checkout

      # Étape 2 : Configurer Docker Buildx
      - name: Configurer Docker Buildx
        uses: docker/setup-buildx-action@v3  # Configure Docker Buildx pour la construction d'images multiplateformes

      # Étape 3 : Se connecter au registre GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2  # Se connecte à GitHub Container Registry pour pousser l'image
        with:
          registry: ghcr.io  # Spécifie le registre GitHub Container Registry
          username: ${{ github.actor }}  # Utilise l'acteur GitHub pour l'authentification
          password: ${{ secrets.GITHUB_TOKEN }}  # Utilise le token GitHub pour l'authentification (par défaut)

      # Étape 4 : Construire et pousser l'image Docker
      - name: Build Docker image
        uses: docker/build-push-action@v5  # Action pour construire et pousser l'image Docker
        with:
          context: .  # Spécifie le contexte de la construction Docker (répertoire actuel)
          push: true  # Indique que l'image doit être poussée vers le registre
          tags: ghcr.io/aniskhal25/ue19-lab-05  # Tag de l'image Docker
          
      # Étape 5 : Scanner l'image Docker avec Trivy pour les vulnérabilités
      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@master  # Utilise Trivy pour scanner l'image Docker
        with:
          image-ref: ghcr.io/aniskhal25/ue19-lab-05  # Référence de l'image à scanner
          

      
     
